export const protectedRoutes = [
  { path: 'dashboard' },
  { path: 'profile' },
  { path: 'career-profile' },
  { path: 'job-discovery' },
  { path: 'applications' },
  { path: 'saved-jobs' },
  { path: 'settings' },
  { path: 'agents' },
  { path: 'skill-gaps' },
  { path: 'roadmap' },
  { path: 'portfolio' },
  { path: 'analytics' },
  { path: 'billing' },
];